slam_toolbox:
  ros__parameters:
    use_sim_time: true  # Sử dụng thời gian thực thay vì thời gian giả lập
    map_file_name: "map"  # Tên file lưu bản đồ
    resolution: 0.05  # Độ phân giải bản đồ (mỗi ô vuông là 0.1m)
    max_laser_range: 12.0  # Phạm vi tối đa của laser (m)
    minimum_time_between_scan_matching: 0.7  # Thời gian giữa các lần scan matching (s)
    transform_timeout: 0.2  # Thời gian timeout (kiểu double)
    use_scan_matching: true  # Sử dụng scan matching để giảm lỗi bản đồ
    use_pose_graph: true   # Sử dụng pose graph để tối ưu hóa bản đồ
    laser_scan_topic: "scan"  # Topic của LaserScan
    odom_frame: "odom"  # Khung tham chiếu của odometry
    base_frame: "base_link"  # Khung tham chiếu của robot
    map_frame: "map"  # Khung tham chiếu của bản đồ
    publish_period: 0.67  # Thời gian giữa các lần xuất bản dữ liệu (s)

